### ISSUE TITLE
tape-nock configuration does not allow for lockdown access to 127.0.0.1

### ISSUE THREAD

**Issue by rmeyer-taos** [Flet/tape-nock#23]
I have been having this issue on a private repo project so I have created a minimal install project to demonstrate the issue I have been seeing. It is possible I have massively failed on the configuration. 

I have done the configuration in two ways
-  import as in: https://github.com/Blue-Dog-Archolite/tape-nock-testing-failure/blob/master/test/users/test-otherUserRoute.js
- direct declaration as in: https://github.com/Blue-Dog-Archolite/tape-nock-testing-failure/blob/master/test/users/test-ldapStaticFetch.js

In both cases, the display does not record either the `before` or `after` functions being called. 

There is also a `test-works.js` file showing functionality without `tape-nock`

https://github.com/Blue-Dog-Archolite/tape-nock-testing-failure is the public project. 

```npm install```

```npm run test``` 

![rmeyer thief-thinkpad-p71 -dev-taos-minimalnockback_006](https://user-images.githubusercontent.com/41446919/44492447-cbe95c00-a621-11e8-82b5-ea1872315129.png)

**Comment by big-kahuna-burger** [comment]
I'm wondering if you already export `test` from `nock-setup.js`, when why are you setting it up multiple times in `test-ldapStaticFetch.js` ?
https://github.com/Blue-Dog-Archolite/tape-nock-testing-failure/blob/master/test/users/test-ldapStaticFetch.js#L9

That should be ```var test = require(appRoot + '/test/nock-setup.js');```
Don't setup `tape-nock` again bellow, and just use whatever you have exported as you would use  `tape`

**Comment by rmeyer-taos** [comment]
You are brilliant. I was too deep in the rabbit hole to see that I was duplicating the includes.

Thank you so much. Just made my week.

**Comment by big-kahuna-burger** [comment]
Have a good one :)
