### ISSUE TITLE
Test with nock beta

### ISSUE THREAD

**Issue by paulmelnikow** [Flet/tape-nock#24]
Hi! We've started making beta releases toward the next major release of nock. Would you be up for giving one of them a shot in some tests for this library to help us ensure compatibility?

[![npm](https://img.shields.io/npm/v/nock.svg)][npmjs]
[![npm@beta](https://img.shields.io/npm/v/nock/beta.svg)][npmjs]

[npmjs]: https://www.npmjs.com/package/nock

Note that v11, when it's released, will drop support for Node 6.

**Comment by big-kahuna-burger** [comment]
Sure. Not that I have time atm, but expect me to bump and test in the next few days.
Cheers!

**Comment by big-kahuna-burger** [comment]
Ok, so we synced our 1.6.1 with `nock@^10.0.6` major.
And there is now `tape-nock@2.0.0-0` tagged with `next` tag at npm using `nock@10.0.0-beta.4`.

I did have to drop support of node 6 [here](https://github.com/Flet/tape-nock/compare/beta#diff-354f30a63fb0907d4ad57269548329e3R3) so ping me again here so I can _transpile_ back when you go to 11.

Cheers.

**Comment by paulmelnikow** [comment]
Awesome, thanks!

Do you mean 11.0.0-beta.4?

Nock depends on some Node internals and I’m not sure if those will work on Node < 8 even if transpiled. I’ll be curious to know if it works.
