### ISSUE TITLE
Competition :)

### ISSUE THREAD

**Issue by simlu** [Flet/tape-nock#29]
Just discovered your package! I maintain a package with very similar capabilities: https://github.com/blackflux/node-tdd

Feel free to take a look, it's a custom brewed based on thousands of tests. 

PS: Not really trying to compete, but you might get inspired. We have some cool features, like enforcing request ordering checks, etc

**Comment by big-kahuna-burger** [comment]
Hey @simlu!
Well, they both depend on `nock` but that's where similarities end. They are really different in how you use them for tdd. This package is to be used by `tape` users and not intended to be drop in replacement for tape, but rather as a glue for `tape` and `nock` to work together in e2e server testing scenarios. Closing this, and nudging @Flet to see if he finds something useful going forward.

**Comment by simlu** [comment]
Hey! Thanks for getting back.

Just some things we do that you might find interesting:
- automatic healing of cassettes when the request body changes (this is a cli arg)
- checking request ordering (ensuring cassette recording is correct) - healing can fix this as well
- checking if there are any unmatched recordings in the cassette
- checking if unknown recordings exist
- allowing headers to not be recorded in cassette

I'm sure there is more, but that's all I can think of right now

**Comment by simlu** [comment]
Also: Replacement, glue... All the same. Our packages do very, very similar things.
