### ISSUE TITLE
NetConnectNotAllowedError with lockdown mode and recorded fixtures

### ISSUE THREAD

**Issue by goodmind** [Flet/tape-nock#5]
Hi!

I have a issue with `mode: 'lockdown'`
There is recorded fixtures, but this seems don't work
Nock still trying to go out to the internet

```
 { [NetConnectNotAllowedError: Nock: Not allow net connect for "api.telegram.org:443/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getUpdates"]
  name: 'NetConnectNotAllowedError',
  message: 'Nock: Not allow net connect for "api.telegram.org:443/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getUpdates"',
  response: undefined }
```

**Comment by Flet** [comment]
Hmm, May need to delete the recordings and re-record to capture this too? Not sure.

**Comment by goodmind** [comment]
Oh, I figured out that fixtures only works in `test('...', t => {})`, but not for global vars
