### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by goodmind** [Flet/tape-nock#6]
Is it possible to provide typescript definitions for this package?

**Comment by Flet** [comment]
Sure, I don't know how to do this, but PR is welcome and will add as a collaborator to this repo and give publish rights.

**Comment by Flet** [comment]
Thanks for the PR! Closed via #7 

Added you as a collaborator here and gave publish rights on npm.

Published as `tape-nock@1.2.2`

**Comment by goodmind** [comment]
@Flet can I publish package whenever i want?

**Comment by Flet** [comment]
Sure can! Ideally, if you have non-trivial updates they should be sent in via a pull request for a sanity check. If its small stuff (i.e. README updates) feel free to publish.

If for whatever reason I'm unresponsive to pull requests, use your best judgement and publish as you see fit (adhering to semantic versioning).

Read the collaborating guidelines here for more info: https://github.com/Flet/tape-nock/blob/master/CONTRIBUTING.md#collaborating-guidelines
