### ISSUE TITLE
tape test.only

### ISSUE THREAD

**Issue by goodmind** [Flet/tape-nock#9]
It seems that `tape-nock` not working with `test.only` method?

https://github.com/substack/tape#testonlyname-cb

**Comment by goodmind** [comment]
@Flet ?

**Comment by Flet** [comment]
Yep, looks like a bug! :)

**Comment by goodmind** [comment]
Fixed by #10 (but need to write tests for it)

**Comment by Flet** [comment]
Closed via #10
